<?
$aMenuLinks = Array(
    Array(
        "О компании",
        "#SITE_DIR#company/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Сотрудники",
        "#SITE_DIR#company/team/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Вакансии",
        "#SITE_DIR#company/vacancy/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Бренды",
        "#SITE_DIR#company/brands/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Наши магазины",
        "#SITE_DIR#company/shops/",
        Array(), 
        Array(), 
        "" 
    ),
     Array(
        "Контакты",
        "#SITE_DIR#company/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "#SITE_DIR#company/news/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Акции",
        "#SITE_DIR#company/actions/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Услуги",
        "#SITE_DIR#company/services/",
        Array(),
        Array(),
        ""
    ),
);
?>