<?
$MESS["UF_USER_ID"] = "User ID";
$MESS["UF_FAV_ID"] = "Favorite ID";
$MESS["UF_XML_ID"] = "Element ID";
$MESS["UF_BG"] = "Background";
$MESS["UF_BUTTONS"] = "Buttons";
$MESS["UF_SHADOWS"] = "Shadows";
$MESS["UF_THEME"] = "Theme";
$MESS["UF_NAME"] = "Name";
$MESS["UF_FILE"] = "File";
$MESS["UF_LINK"] = "Link";
$MESS["UF_SORT"] = "Sort";
$MESS["UF_DEF"] = "Default";
$MESS["UF_XML_ID"] = "XML_ID";
$MESS["UF_DESCRIPTION"] = "Description";
$MESS["UF_FULL_DESCRIPTION"] = "Long description";
$MESS["UF_EXTERNAL_CODE"] = "External Code";
$MESS["SHORT_DESC_1marka"] = "Existing since 2001, «1MarKa» is producing high quality and good prices.";
$MESS["LONG_DESC_1marka"] = "<p>A five hundred employers staff creating european quality goods, holding nothing back against worlds wide brands.</p><br />
<p>Such complex method allow to perform any, exclusive and induividual, small and large scale orders in no time.</p><br />
<p>Production assortment of «1MarKa» constantly expanding and modernizing. Main proud of them is their patented material called &laquo;POLITITAN&raquo;, which allow wide possibilities for production of excluxive pieces of bath furniture.</p><br />
<p>Modern trchnologies, own R&D, state of the art equipment, and high quality personel ensures will to perfection and guarantee high quality production. It comply with original and exclusive design patterns. Main pros of «1МарКа» is good price/quality ratio.</p>";
$MESS["SHORT_DESC_apollo"] = "Exists since 1996 and don't stop it's developing pace in in times of hardships and crysises.";
$MESS["LONG_DESC_apollo"] = "<p>Optimal price/quality ratio of all assortment wares, which consist of 700 models of different forms, sizes and functioning ( bath tubs with sauna, shower walls and decorative doors, finnish saunas, hydromassage baths, jacuzzi, simple baths, bath furniture, usual and electronic pans, mixers and shower panels, and other).</p><br />
<p>&laquo;Appollo&raquo; constantly research and employ new design solutions and shapes for whole production list, creates new ways of development, uses innovative technologies, exclusive worldwide, refreshes and restyles obsolete models with last market achievements and trands. Each piece of bath furniture is multifunctional, compact reliable.</p><br />
<p>&laquo;APPOLLO&raquo; today is one of the &laquo;whales&raquo; of sanitary world. For last 3 years &laquo;APPOLLO&raquo; holds first positions by sale shares on Russian market.</p>";
$MESS["SHORT_DESC_aquavita"] = "Aquavita baths made from 100% solid acrilic &laquo;plexiglas&raquo;(Германия).";
$MESS["LONG_DESC_aquavita"] = "<p>This material have near perfect parameters for creation of baths, guarantees think shine with exquisite surface quality, IR and UV proof with chemical and corrosive resitance. Hard to scratch, easy to repair. Acrilic preserve shape for many years, which means best worldwide standards and is used by famous european bath producers.</p><br/>
<p>For bath reinforcements of inner surface, bottom, seats and boards special liners, which enhance hardness and longevity. Metal frame of bath specially prepared for wet environment, covered with powder enamel and have lateral stubs. Frame is strongly attached to the reinforcements with screws. Bath can be leveled with help of adjusting legs. Such baths are easy to install and use, due to solid construction.</p>";
$MESS["SHORT_DESC_bas"] = "LTD «BASS» is one of leading acrilic bath and shower tubes producers in Russia, due to 15 years on market of bath furniture";
$MESS["LONG_DESC_bas"] = "<p>LTD «BASS» employs positive selfimage in among customers  and partners of «BAS» acrilic baths. «BAS» brand is  easily sold in all corners of Russia, and also in Kazakhstan and Belarus.</p><br />
<p>Current «BAS» production list consist of 30 baths, blinds, shower tubes and walls. Company have strong production capabilities and qualified staff, all production is made with italian and american equipment. Bath shaping is made bu italian vacuum machines produced by SELF width IR areal heating, which made possible wide spectrum of quality production of different form and sizes.</p>";
$MESS["SHORT_DESC_cersanit"] = "We are famous Poland producer of bath furniture. Already several decades we successfully creating and selling our products, such as ceramic tiles, bath furniture, baths, showers, acrilic baths, grounds and other acrilic products.";
$MESS["LONG_DESC_cersanit"] = "<p>As a trusted brand name manufacturer, we offer complete solutions that combine high quality, functionality and style.</p><br />
<p>Our mission - to support you in the difficult process of repair and construction of your bathroom. Bathrooms are small - a challenge for us! They are difficult to equip? - Through our products, they have a chance to become pleasant to use for all family members, functional, spacious and most importantly not devoid of individual character.</p><br />
<p>Since its inception, we have appreciated the development and innovation - for example, we were the first brand in Poland, presented cupboard under the sink in the early 90s. Nowadays among our offer you can find many products that are the result of the introduction of modern technologies and solutions that meet the specific needs of our customers and becoming ideal for a small bathroom, ensuring the comfort and safety of their use. A perfect example of this two conceptual series launched in production in recent years - Pure and Nano, the collection encompasses all elements of plumbing, ceramics, furniture and baths.</p>";
$MESS["SHORT_DESC_eago"] = "EAGO - it is the best in China plumbing and factory company EAGO Sanitary Ware Co - one of the largest and most important companies in the country. The factory is located near the city of Foshan (Guangdong province) in an area of 250 thousand square meters! Is considered the founding date of the brand in 1996.";
$MESS["LONG_DESC_eago"] = "<p>For a short time the Chinese sanitary ware found throughout the world - it is actively marketed in the United States, Canada, Belgium, Russia and other countries. However, it is not correct to call this the Chinese sanitary ware, because it is made on a modern European equipment checked by Western technology. Products are available in 200 countries.</p><br />
<p>List of products, which are produced by EAGO, is impressive: it jetted acrylic bathtubs, shower stalls and boxes, shower panels, as well as sanitary ware products - sinks, toilets, bidets. All products meet strict international standards of quality and safety. Thus, products EAGO has a quality certificate ISO9001-2000, meets European standards UPC, TUV-CE, CUPC, ETL. Activities of this booming company recognized with high ranks and awards: EAGO is in the top 100 best companies of China, in the top 10 of the best producers of ceramic sanitary ware and the ten most developed export companies. Companies really have something to be proud of, and it continues to evolve in this direction.</p>";
$MESS["SHORT_DESC_kolpasan"] = "The company is one of the largest enterprises in southern Europe for the production of equipment for bathrooms.";
$MESS["LONG_DESC_kolpasan"] = "<p>The company is proud of high-quality products for the decor of bathrooms Kolpa San. The company is located in Metlika in southern Slovenia. Located in the heart of Europe our company enables effective impact on the commercial network and the rapid implementation of its products in the market. On the European market, with its high requirements, we sell 80% of our products.</p><br />
<p>The program Kolpa services bathtubs and showers, showers and massage elements - external massage pools, whirlpool tubs and cabins. Products program Kolpa San thanks to its traditional quality stored permanently. They can be found on the classic functionality that accompany modern design. With a wide range of products, here everyone can find mozheli to your liking, and tried in fact, feel the positive energy, freedom and complete trust in the brand.</p><br />
<p>The company follows the principle Kolpa &laquo;pure performance&raquo;, which means the rational consumption of raw materials, a high degree of efficiency and better quality products. Caring for the environment proves the environmental standard ISO 14001.</p>";
$MESS["SHORT_DESC_loranto"] = "The company is one of the largest enterprises in southern Europe for the production of equipment for bathrooms.";
$MESS["LONG_DESC_loranto"] = "<p>The company is proud of high-quality products for the decor of bathrooms Kolpa San. The company is located in Metlika in southern Slovenia. Located in the heart of Europe our company enables effective impact on the commercial network and the rapid implementation of its products in the market. On the European market, with its high requirements, we sell 80% of our products.</p><br />
<p>The program Kolpa services bathtubs and showers, showers and massage elements - external massage pools, whirlpool tubs and cabins. Products program Kolpa San thanks to its traditional quality stored permanently. They can be found on the classic functionality that accompany modern design. With a wide range of products, here everyone can find mozheli to your liking, and tried in fact, feel the positive energy, freedom and full e brand trust.</p><br />
<p>The company follows the principle Kolpa &laquo;pure performance&raquo;, which means the rational consumption of raw materials, a high degree of efficiency and better quality products. Caring for the environment proves the environmental standard ISO 14001.</p>";
$MESS["SHORT_DESC_relisan"] = "Relisan company engaged in wholesale deliveries of sanitary ware.";
$MESS["LONG_DESC_relisan"] = "<p>Relisan collaborates with leading European manufacturers, preferring the optimal combination of price and quality.</p><br />
<p>Conduct a careful selection among the proposals, Relisan allows creating of bathrooms special space harmony, sensuality and aesthetics.</p><br />
<p>Geography RELISAN - covers all the subjects of the Russian Federation. We are always ready to process your request and provide you with the contact details for your nearest location by our representative. We appreciate your convenience!</p>";
$MESS["SHORT_DESC_roca"] = "Roca The company started its activity with the production of cast iron radiators for home heating systems in its own factory in Gava, a suburb of Barcelona.";
$MESS["LONG_DESC_roca"] = "<p>After the start of the production of radiators, the company added in its product range boilers. In 1929 Roca entered the market with its production tubs.</p><br />
<p>Roca has always closely followed the changes in the attitude of the society to water, basic natural resources with which it works, and so in 1936 the company decided to start the production of glass-ceramics for bathrooms. After that, in 1954, the company began production of copper products.</p><br />
<p>In the 1990s, the Group has taken the first step towards the development of the international arena, opening branches and signing contracts with local companies, manufacturers of leading brands. In addition to Portugal and France Roca began working in the UK, Germany, Italy, Russia, Morocco, Argentina, Brazil and China.</p><br />
<p>In 2005 Roca announced ambitious strategic development plan, oriented primarily on equipping bathrooms, and achieved world leadership in this area in 2006.

Currently, the network of outlets Roca covers more than 135 countries, deliveries are made with 76 of their own businesses, which employ more than 20 thousand people.</p>";
$MESS["SHORT_DESC_triton"] = "Quality European level at affordable price - is the foundation of brand strategy Triton.";
$MESS["LONG_DESC_triton"] = "<p>On the market - the company a little more than 10 years. Its specialization - rather narrow and includes only two segments. Brand manufactures furniture for bathrooms and acrylic bathtubs.</p><br />
<p>The entire product range of the brand unparalleled quality, distinctive style and innovative design. The cost of goods in this case - is available to consumers with an average income.</p><br />
<p>Chairs for Triton - practical and convenient to use. Projects are developed in the system of three-dimensional design. This allows the use of the area bathrooms - quite effectively. A thin-walled metal frames boxes help designers to save space.</p><br />
<p>Cabinet fronts are made of MDF and covered with waterproof tape. The doors are equipped with silent closing. A Mirror coated silver amalgam. Serve furniture Triton - for decades.</p><br />
<p>The real pride of the manufacturer - hot tubs. Here Triton reached the true heights. The quality of materials is given special attention. The entire line of models manufactured on modern American equipment. Raw materials it uses - European - the highest quality. Body - made of reinforced plastic coated with a resin and a thin layer of acrylic.</p><br />
<p>Even budget baths can be equipped with a function underwater lighting and chromotherapy. Furthermore, these additional decorative options have therapeutic effects. Treatment of color - a technique widespread in recent years. It is proved that the effect of color on the body - actually quite high. It has an effect on mood, and physical health.</p>";
$MESS["SHORT_DESC_vayer"] = "Employees Swisspool Balneo SA - manufacturer of baths Vayer, traditionally focus on maximizing the reliability of the products, always working to improve the quality of the goods, which must fully comply with the most demanding buyers.";
$MESS["LONG_DESC_vayer"] = "<p>The stunning success of baths Vayer model in European countries is due, primarily, innovative technology solutions, high quality materials used in the manufacture of sanitary ware, strict adherence to safety standards, attractive appearance of the product. Company Swisspool Balneo SA based in Cormoret (Switzerland). Over recent years, the organization is a living example of the implementation of the most modern trends in the production of sanitary products in Western Europe.</p><br />
<p>Bath Vayer is technically completed sanitary products, which is characterized by visual lightness and ergonomics. In developing its products, the company cooperates with Swisspool famous designers in Europe. Vayer baths can be seen in the elite boutiques of sanitary products, located in cities such as Paris, Brussels, Geneva, Zurich, etc. Products Swisspool used when equipped with modern five-star hotel, resort, located on the French coast. Bath Vayer - is the choice of those who are always up to date!</p>";
$MESS["SHORT_DESC_iddis"] = "IDDIS - a Russian trademark, established and registered company &laquo;SCR&raquo; in 2004.";
$MESS["LONG_DESC_iddis"] = "<p>The main goal of the company in the development process was to ensure the quality of Russian consumers, contemporary and affordable plumbing, and it has been successfully achieved.</p><br />
<p>Today trademark IDDIS takes on the Russian market and a strong position thanks to the superior quality of its plumbing, its attractive price and modern design enjoys popularity among buyers and respect. Products represented in more than 2,000 retail sites across Russia and the CIS countries (Belarus and Kazakhstan), indicating that the main point: our consumers appreciate products brand IDDIS, and the number of grateful customers consistently increasing.</p>";
$MESS["SHORT_DESC_grohe"] = "Grohe AG - manufacturer of sanitary fittings, faucets and accessories. The company was founded in 1936 by Friedrich Grohe.";
$MESS["LONG_DESC_grohe"] = "<p>Has offices in 15 countries. Grohe headquarters is located in Dusseldorf, Germany.</p><br />
<p>GROHE manufacturer of faucets and shower sets for the bathroom and kitchen, automatic and electronic faucets public and commercial, installation and flushing systems for overhead plumbing system concealed wall mounting.</p><br />
<p>The share of GROHE AG accounts for about 8% of the world market. In 2007, sales of manufactured GROHE sanitary fittings for kitchens, baths and showers, automatic fittings for the commercial and public sectors, and installation and flushing systems amounted to 1.017 million euros.</p>
<p>Headquarters Grohe AG. Germany, Dusseldorf. At GROHE 6 production sites, three of which are located abroad, in particular in Portugal, Thailand and Canada. The company sells more than 82% of its products outside Germany. Worldwide in enterprises GROHE employs about 5,000 people.</p><br />
<p>GROHE company manufactures its products in its own design center. For many years the company has been honored with the most famous in the world of design awards, such as the «Red dot», «IF design awards», and «Good Design Awards».</p>";
$MESS["SHORT_DESC_hansgrohe"] = "Hansgrohe SE produces and manufactures products under two brands: Hansgrohe, Axor, Pharo. For more than a century the company, the management of which all is also in the hands of the same family, is a trendsetter in the world of modern, high-tech designer bathrooms.";
$MESS["LONG_DESC_hansgrohe"] = "<p>His concept of the high culture of water use in the implementation of the company confirmed the most ambitious projects: hotels and public buildings, private residences, royal palaces, cruise liners and luxury yachts.</p>
<p>Our wide palette of quality products allows even the most discerning find what they need.</p>
<p>High quality bathrooms show hospitality hotel, whether grand hotel or a small elegant boutique hotel.</p>
<p>Scenario for the bathroom from the best hotels</p>
<p>Dining room in luxury apartment in Munich Yoo</p>
<p>In residential building, luxury apartments and even in the palace: everywhere we strive for extraordinary feeling in the bathroom.</p>
<p>individual ideas about luxury bathrooms</p>
<p>Mixers and showers from Hansgrohe have found their home on the open sea.</p>
<p>Ships and yachts</p>
<p>Yerres swimming pool for recycling gray water installation uses Pontos AquaCycle.</p>";
?>