<?
$aMenuLinks = Array(
    Array(
        "О компании",
        "/company/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Сотрудники",
        "/company/team/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Вакансии",
        "/company/vacancy/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Бренды",
        "/company/brands/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Наши магазины",
        "/company/shops/",
        Array(), 
        Array(), 
        "" 
    ),
     Array(
        "Контакты",
        "/company/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "/company/news/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Акции",
        "/company/actions/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Услуги",
        "/company/services/",
        Array(),
        Array(),
        ""
    ),
);
?>