<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$aMenuLinks = Array(
    Array(
        "Доставка",
        "/about/dostavka/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Гарантия",
        "/about/garantiya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Возврат",
        "/about/vozvrat_i_obmen/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Бренды",
        "/brands/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог ITPROM",
        "/blog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Компания",
        "/about/o-kompanii/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/about/contacts/",
        Array(),
        Array(),
        ""
    ),
);
?>