<?
$aMenuLinks = Array(
    Array(
        "Информация",
        "/info/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Поставщикам",
        "/info/suppliers/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Гарантия",
        "/info/guaranty/",
        Array(), 
        Array(), 
        "" 
    ),
);
?>