<?
$aMenuLinks = Array(
    Array(
        "Информация",
        "#SITE_DIR#info/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Поставщикам",
        "#SITE_DIR#info/suppliers/",
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Гарантия",
        "#SITE_DIR#info/guaranty/",
        Array(), 
        Array(), 
        "" 
    ),
);
?>